# Generated by Django 6.0.1 on 2026-08-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='roll_number',
        ),
    ]
