# Generated by Django 6.0.1 on 2026-02-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_department_subject_attendancesession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='day_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='session_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
