# Generated by Django 6.0.1 on 2026-02-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancesession_day_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='is_present',
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='radius_meters',
            field=models.IntegerField(default=50),
        ),
        migrations.DeleteModel(
            name='AttendanceLog',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
