# Generated by Django 6.0.1 on 2026-02-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendancerecord_is_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='radius_meters',
            field=models.IntegerField(default=100),
        ),
    ]
