# Generated by Django 6.0.1 on 2026-02-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancesession_radius_meters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='radius_meters',
            field=models.IntegerField(default=200),
        ),
    ]
